title: 'Simon Coudeville'
author: 'Simon'
description: 'Personal website for Simon Coudeville'
exclude: ['_site','scss','*scss','Gem*','Guard*','*rb','.sass-cache','.git*','config.rb','*.md','*.json','docroot','node_modules','gulpfile.js','install.sh','lint.yml']
